### ISSUE TITLE
I made a release just for you!

### ISSUE THREAD

**Issue by emg110** [igormuba/crypdonations#1]
Hi there, 
Thanks for using [algorand-qrcode](https://github.com/emg110/algorand-qrcode)
If you need to construct your own QR Code from your specific URIs just pass {**rawUri**: 'yourCustomUri'} as an option and no need for other constituent options (other than styling ones) like wallet, amount, label, note , xnote and asset.
[Version 1.1.2](https://www.npmjs.com/package/algorand-qrcode) is out containing this update just for you. Hope It helps your noble causes.
email me ( emg110@gmail.com ) if you needed any further help.

**Comment by igormuba** [comment]
Thank you for the contribution!

I was not actually using algorand-qrcode, but another QRCode that made it simple to add a title on top of the QRCode image, but I have now changed it to algorand-qrcode and will keep using it and see how people react.
https://github.com/igormuba/crypdonations/commit/f871209bbca7b06389d265c706d5f7dc5a25e36f

I have tried to pay it forward by doing what I could with the little time I have today, by using it and making a PR and adding this new rawUri to your readme
https://github.com/emg110/algorand-qrcode/pull/2
